name = "Dendrometry"
uuid = "75af3865-8f9e-41a1-875e-d9239fa7d34a"
version = "1.0.0-DEV"
authors = ["marcosdanieldasilva <marcosdasilva@5a.tec.br> and contributors"]

[deps]
AllometricModels = "1c853ebb-f589-4e8a-a6f3-211670fabf15"

[sources]
AllometricModels = {path = "C:\\Users\\marco\\OneDrive\\Documents\\Julia\\AllometricModels"}

[compat]
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
