name = "Dendrometry"
uuid = "75af3865-8f9e-41a1-875e-d9239fa7d34a"
version = "1.0.0-DEV"
authors = ["marcosdanieldasilva <marcosdasilva@5a.tec.br> and contributors"]

[deps]
AllometricModels = "1c853ebb-f589-4e8a-a6f3-211670fabf15"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StatsModels = "3eaba693-59b7-5ba5-a881-562e759f1c8d"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[sources]
AllometricModels = {rev = "master", url = "https://github.com/marcosdanieldasilva/AllometricModels.jl.git"}

[compat]
AllometricModels = "1.0.0"
CairoMakie = "0.15.8"
DataFrames = "1.8.1"
LinearAlgebra = "1.12.0"
StatsModels = "0.7.7"
Tables = "1.12.1"
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
